dangerouslyAllowAllBuilds: true
minimumReleaseAge: 0
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar
  - semver
packages:
  - .
trustLockfile: true
overrides:
  esbuild: ^0.28.1
  semver: ^7.5.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - '@swc/core'
